export const strings = {
  widgetTitle: 'L4 Support',
  launcherLabel: 'Open support',
  launcherText: 'Support',
  closePanel: 'Close',
  closePanelLabel: 'Close support',
  tabsLabel: 'Support widget tabs',
  helpTab: 'Help',
  roadmapTab: 'Roadmap',
  supportTitle: 'My Support',
  submitTitle: 'New case',
  subjectLabel: 'Subject',
  descriptionLabel: 'Description',
  categoryLabel: 'Category',
  severityLabel: 'Severity',
  submitButton: 'Submit',
  replyButton: 'Reply',
  noCases: 'No cases yet',
  noHelpArticles: 'No help articles yet',
  noRoadmap: 'No public roadmap yet',
  typeToSearch: 'Type at least 3 characters to search.',
  searchHelpLabel: 'Search help articles',
  searchHelpLoading: 'Searching help articles...',
  searchHelpError: 'Could not search help articles.',
  helpDeflectButton: 'Still stuck? File a case',
  casesLabel: 'Support cases',
  casesLoading: 'Loading cases...',
  casesError: 'Could not load cases.',
  selectCase: 'Select a case.',
  caseLoading: 'Loading case...',
  caseError: 'Could not load this case.',
  caseUnavailable: "This case isn't available.",
  subjectRequired: 'Subject is required.',
  caseSubmitted: 'Case submitted.',
  replyLabel: 'Reply',
  replyRequired: 'Reply is required.',
  roadmapLoading: 'Loading roadmap...',
  roadmapError: 'Could not load roadmap.',
  roadmapStatusPlanned: 'Planned',
  roadmapStatusInProgress: 'In progress',
  roadmapStatusCompleted: 'Completed',
  roadmapStatusDeferred: 'Deferred',
  roadmapStatusCancelled: 'Cancelled',
  roadmapStatusOther: 'Other',
  genericError: 'Support is temporarily unavailable.',
  sessionExpired: 'Your support session has expired.',
  notEnabled: "Support isn't enabled for your account.",
  rateLimited: 'Too many support requests. Try again later.',
  validationError: 'The support request was not valid.',
  boundaryFallback: 'Support is temporarily unavailable.',
};
