export const strings = {
  widgetTitle: 'L4 Support',
  headerTitle: 'Support',
  headerMark: 'L4',
  separatorDot: ' · ',
  launcherLabel: 'Open support',
  launcherText: 'Support',
  closePanelGlyph: '×',
  closePanelLabel: 'Close support',
  tabsLabel: 'Support widget tabs',
  helpTab: 'Help',
  roadmapTab: 'Roadmap',
  supportTitle: 'My Support',
  supportSearchPlaceholder: 'Search tickets & answers',
  supportNewButton: '+ New',
  supportBackButton: 'Back',
  supportAnswersTitle: 'Answers',
  supportTicketsTitle: 'Your tickets',
  supportFilterOpen: 'Open',
  supportFilterWaiting: 'Waiting on you',
  supportFilterResolved: 'Resolved',
  supportCaseNumberFallback: 'Case',
  supportEmptyThreadTitle: 'Select a case',
  supportNewThreadTitle: 'New case',
  supportCreateHint: 'Tell us what happened. Vega starts triage immediately.',
  supportUnknownStatus: 'Unknown',
  supportStatusNew: 'New',
  supportStatusProgress: 'In progress',
  supportStatusWaiting: 'Waiting on you',
  supportStatusResolved: 'Resolved',
  supportStatusTransition: 'Status ->',
  supportAutoTriaged: 'auto-triaged',
  supportEventUpdated: 'updated',
  supportEventCaseAssigned: 'Escalated to a specialist',
  supportOpenedPrefix: 'Opened',
  supportCategoryPrefix: 'Category',
  supportYouAuthor: 'You',
  supportAgentAuthor: 'L4 Support',
  supportVegaBadge: 'VEGA · AI',
  replyPlaceholder: 'Reply — Vega answers instantly, a human steps in when it matters',
  submitTitle: 'New case',
  subjectLabel: 'Subject',
  descriptionLabel: 'Description',
  categoryLabel: 'Category',
  severityLabel: 'Severity',
  submitButton: 'Submit',
  replyButton: 'Send',
  noCases: 'No cases yet',
  noHelpArticles: 'No help articles yet',
  noRoadmap: 'No public roadmap yet',
  typeToSearch: 'Type at least 3 characters to search.',
  searchHelpLabel: 'Search help articles',
  searchHelpLoading: 'Searching help articles...',
  searchHelpError: 'Could not search help articles.',
  helpDeflectButton: 'Still stuck? File a case',
  casesLabel: 'Support cases',
  casesLoading: 'Loading cases...',
  casesError: 'Could not load cases.',
  selectCase: 'Select a case.',
  caseLoading: 'Loading case...',
  caseError: 'Could not load this case.',
  caseUnavailable: "This case isn't available.",
  subjectRequired: 'Subject is required.',
  replyLabel: 'Reply',
  replyRequired: 'Reply is required.',
  roadmapLoading: 'Loading roadmap...',
  roadmapError: 'Could not load roadmap.',
  roadmapStatusPlanned: 'Planned',
  roadmapStatusInProgress: 'In progress',
  roadmapStatusCompleted: 'Completed',
  roadmapStatusDeferred: 'Deferred',
  roadmapStatusCancelled: 'Cancelled',
  roadmapStatusOther: 'Other',
  genericError: 'Support is temporarily unavailable.',
  sessionExpired: 'Your support session has expired.',
  notEnabled: "Support isn't enabled for your account.",
  rateLimited: 'Too many support requests. Try again later.',
  validationError: 'The support request was not valid.',
  boundaryFallback: 'Support is temporarily unavailable.',
};
